routes/web.php
<?php

Route::get('/', 'PageController@home')->name('_root_');


// routes for admin
Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');
Route::post('admin/logout', 'Admin\LoginController@logout');
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function(){
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/phpinfo', 'DashboardController@phpinfo');
    Route::resource('pages', 'PageController');
    Route::post('pages/order', 'PageController@order')->name('pages.order');
    Route::get('pages/showhide/{page}', 'PageController@showhide')->name('pages.showhide');
    Route::get('pages/photodelete/{page}', 'PageController@photodelete')->name('pages.photodelete');
    Route::resource('ads', 'AdController');
    Route::get('ads/showhide/{ad}', 'AdController@showhide')->name('ads.showhide');
    Route::post('ads/order', 'AdController@order')->name('ads.order');
    Route::resource('slides', 'SlideController');
    Route::post('slides/order', 'SlideController@order')->name('slides.order');
    Route::get('slides/showhide/{slide}', 'SlideController@showhide')->name('slides.showhide');
    Route::resource('labels', 'LabelController');
    Route::resource('settings', 'SettingController');
    Route::resource('reviews', 'ReviewController');
    Route::get('reviews/approve/{review}', 'ReviewController@approve')->name('reviews.approve');
    Route::get('reviews/cancel/{review}', 'ReviewController@cancel')->name('reviews.cancel');
    Route::resource('socials', 'SocialController');
    Route::resource('admins', 'AdminController');
    Route::resource('posts','PostController');
    Route::get('posts/showhide/{slide}', 'PostController@showhide')->name('posts.showhide');
    Route::resource('events', 'EventController');
    Route::get('events/photodelete/{event}', 'EventController@photodelete')->name('events.photodelete');
    Route::resource('videos','VideoController');
    Route::resource('albums','AlbumController');
    Route::post('albums/photodelete', 'AlbumController@photodelete')->name('albums.photodelete');
    Route::resource('blogs','BlogController');
    Route::resource('courses','CourseController');
    Route::get('course-application','CourseApplicationController@index')->name('course.application');
    Route::get('course-application/{id}','CourseApplicationController@view')->name('course.application.view');
    Route::get('password/change', 'DashboardController@passwordchange')->name('password.change');
    Route::post('password/change', 'DashboardController@passwordstore');
    Route::resource('students','StudentController');
    Route::resource('teachers','TeacherController');
    Route::resource('documents', 'DocumentController');
});


Route::group(['middleware' => ['auth']], function(){
    Route::get('profile', 'UserController@profile')->name('profile');
});

Auth::routes();

$router = app()->make('router');
$pages = App\Page::all();
foreach ($pages as $page) {
    if($page->slug == 'contact-us'){
        $router->get($page->slug, 'PageController@contact');
        $router->post($page->slug, 'PageController@contactmail')->name('contactmail');
    } elseif($page->slug == 'reviews'){
        $router->get($page->slug, 'PageController@review');
    } elseif($page->slug == 'news-updates'){
        $router->get($page->slug, 'PageController@newslist');
    } elseif($page->slug == 'courses'){
        $router->get($page->slug, 'PageController@courses')->name('courses');
    } elseif($page->slug == 'gallery'){
        $router->get($page->slug, 'PageController@gallery')->name('gallery');
    } elseif ($page->slug == 'video-gallery') {
        $router->get($page->slug, 'PageController@video')->name('video');
    } elseif ($page->slug == 'photo-gallery') {
        $router->get($page->slug, 'PageController@photogallery')->name('photo.gallery');
    } elseif ($page->slug == 'blogs') {
        $router->get($page->slug, 'PageController@blogs');
    } elseif ($page->slug == 'notice') {
        $router->get($page->slug, 'PageController@notice');
    }
    elseif ($page->slug == 'event') {
        $router->get($page->slug, 'PageController@event');}
    elseif ($page->slug == 'teachers') {
        $router->get($page->slug, 'PageController@teachers');
    } elseif ($page->slug == 'document') {
        $router->get($page->slug, 'PageController@document')->name('document');
        $router->post($page->slug, 'PageController@document_auth');
    }elseif($page->slug <> '/'){
        $router->get($page->slug, 'PageController@index');
    }
}

Route::post('class-book','ClassBookingController@book')->name('class.book');
Route::get('gallery/photo-gallery/{slug}', 'PageController@singlegallery')->name('single.gallery');
Route::post('reviews', 'PageController@reviewsave')->name('review');
Route::get('news-updates/{slug}','PageController@singlenews')->name('singlenews');
Route::get('blogs/{slug}','PageController@singleblog')->name('single.blog');
Route::get('events/{id}','PageController@singleevent')->name('single.event');
Route::get('courses/{slug}/{title}','PageController@singlecourse')->name('single.course');
Route::get('captcha.jpg', 'CaptchaController@image')->name('captcha');

Route::get('thankyou', 'PageController@thankyou')->name('thankyou');


//Preview email on brower
Route::get('emailview/{id}', function($id) {
    $tablebook = \App\Order::find($id);
    return new \App\Mail\NewOrder($tablebook);
});

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    protected $attributes = [
    	'status' => 1,
    ];

    protected $fillable = [
    	'title', 'document', 'details','course',
    ];
}

app/Http/Controllers/Admin/DocumentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Course;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Document;
use Vmorozov\FileUploads\Uploader;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['documents'] = Document::all();
        return view('admin.document.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['courses']=Course::all();
        return view('admin.document.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request);
        $this->validate($request, [
            'course'=>'required',
            'title' => 'required',
            'document' => 'required',
        ]);
       
        $data = array(
            'course' => $request->course,

            'title' => $request->title,

            'details' => $request->details,
        );

        $doc = Document::create($data);
        if ($request->hasFile('document')) {
            $document_name = str_slug($request->title) . '-'.$doc->id . '.'.$request->document->extension();
            $path = $request->document->move('uploads/document/', $document_name);
            $doc->document = $document_name;
            $doc->save();
        }

        return redirect()->route('documents.index')->with('success','Document Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $document)
    {
        return view('admin.document.edit',compact('document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $document)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);

        $data = array(
            'title' => $request->title,
            'course' => $request->course,
            'details' => $request->details,
        );

        Document::where('id',$document->id)->update($data);
        if ($request->hasFile('document')) {
            if($document->document && file_exists(public_path('uploads/document/'.$document->document))){
                unlink(public_path('uploads/document/'.$document->document));
            }
            $document_name = str_slug($request->title) . '-'.$document->id . '.'.$request->document->extension();
            $path = $request->document->move('uploads/document/', $document_name);
            $document->document = $document_name;
            $document->save();
        }
        return redirect()->route('documents.index')->with('success','Document Saved');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Document $document)
    {
        if($document){
            if($document->document && file_exists(public_path('uploads/document/'.$document->document))){
                unlink(public_path('uploads/document/'.$document->document));
            }
            if($document->delete()){
                return redirect()->route('documents.index')->with('success','Document Deleted');
            }
            else{
                return redirect()->route('documents.index')->with('error','Something went wrong');
            }
        }
        else{
            abort();
        }
    }
}

resources/views/admin/document/create.blade.php
@extends('admin.app')

@section('title')
Add Document
@endsection

@section('content')

<div class="content-form">
	<form class="form-horizontal" action="{{ route('documents.store') }}" accept-charset="utf-8" method="post" enctype="multipart/form-data">
		{!! csrf_field() !!}
		@include('admin.document.form')
		<div class="form-group">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
		</div>	
	</form>
</div>
@endsection

resources/views/admin/document/edit.blade.php
@extends('admin.app')

@section('title')
Edit Document
@endsection

@section('content')

<div class="content-form">
	<form class="form-horizontal" action="{{ route('documents.update', $document->id) }}" accept-charset="utf-8" method="post" enctype="multipart/form-data">
		{{ method_field('PUT') }}
		{!! csrf_field() !!}

		@include('admin.document.form')
		
		<div class="form-group">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
		</div>	
	</form>
</div>
@endsection

resources/views/admin/document/form.blade.php
<div class="form-group">
	<label class="col-sm-2 control-label" for="title">Course</label>
	<div class="col-sm-6">
		<select name="course" id="course" class="form-control">
			<option selected="selected">---Select Course---</option>
			<optgroup label="Nepali">
				@foreach($courses as $course)
					@if($course->main_course == 'Nepali')
						<option value="{{ $course->main_course }}">{{ $course->title }}</option>
					@endif
				@endforeach
			</optgroup>
			<optgroup label="Math">
				@foreach($courses as $course)
					@if($course->main_course == 'Math')
						<option value="{{ $course->main_course }}">{{ $course->title }}</option>
					@endif
				@endforeach
			</optgroup>
			<optgroup label="Cultural">
				@foreach($courses as $course)
					@if($course->main_course == 'Cultural')
						<option value="{{ $course->main_course }}">{{ $course->title }}</option>
					@endif
				@endforeach
			</optgroup>

		</select>
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="title">Title</label>
	<div class="col-sm-6">
		<input class="col-md-4 form-control" placeholder="Title" name="title" value="{{ old('title', isset($document) ? $document->title : null) }}" type="text" id="title">
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="details">Details</label>
	<div class="col-sm-10">
		<textarea class="col-md-8 form-control" rows="8" placeholder="Details" name="details" id="details">{{ old('details', isset($document) ? $document->details : null) }}</textarea>
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="document">Document</label>
	<div class="col-sm-6">
		<input type="file" name="document" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
	</div>
</div>

resources/views/admin/document/index.blade.php
@extends('admin.app')

@section('title')
Documents
@endsection

@section('content')


<h3 class="page-title">Documents<a href="{{ route('documents.create') }}" class="btn btn-primary pull-right"><i class="lnr lnr-plus-circle"></i> <span>Add New</span></a></h3>


<div class="content-table">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Title</th>
				<th>Course</th>
				<th>Document</th>
				<th>Created At</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach ($documents as $document)			
			<tr>
				<td>{{ $document->title }}</td>
				<td>{{$document->course}}</td>
				<td><img src="{{ asset('uploads/document/'.$document->document) }}" height="100"></td>
				<td>{{ $document->created_at->format('M d, Y') }}</td>
				<td class="text-right">					
					<a class="btn btn-primary btn-sm" href="{{ route('documents.edit', $document->id) }}"><i class="lnr lnr-pencil"></i></a>
					<div class="pull-right" style="margin-left: 10px;"> 
						<form onsubmit="return confirm('Are you sure?')" action="{{ route('documents.destroy', $document->id) }}" method="post">
							{{ method_field('DELETE') }}
							{{ csrf_field() }}
							<button type="submit" class="btn btn-danger btn-sm"><i class="lnr lnr-trash"></i></button>
						</form>
					</div>
				</td>
			</tr>			
			@endforeach
		</tbody>
	</table>
</div>
@endsection